# Site settings
baseURL = "https://ruchen-portfolio.netlify.app"
languageCode = "en-us"
title = "Portfolio website for Ruchen Shangguan"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Ruchen Shangguan"
  description = "This is a portfolio of my data work"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Ruchen's portfolio"
    subtitle = ""
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "Blogs"
      url = "blogs"

    #[[params.navigation.links]]
      #name = "Generic Blog"
      #url = "blogs/ipsum"

    #[[params.navigation.links]]
      #name = "Elements"
      #url = "elements.html"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    [[params.navigation.button1]]
      name = "My projects"
      url = "blogs"

    # Button Style 2
#    [[params.navigation.button2]]
#      name = "Log In"
#      url = "#"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Hi, this is Ruchen"
    subtitle = "Come explore my data visualisation and analytic pieces."
    buttonText = "Get Started"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "Programming Language Preference"
      subtitle = "What programming languages do Kaggle users recommend?"
      image = "R_Python.jpg"
      url = "blogs/blog3"

    [[params.tiles.showcase]]
      title = "Heart Disease and Risk Factors"
      subtitle = "What risk factors are correlated with heart attacks?"
      image = "heart.jpg"
      url = "blogs/blog4"

    [[params.tiles.showcase]]
      title = "2016 California Contributors plots"
      subtitle = "Who and where did they raise the most money for the 2016 US Presidential election?"
      image = "pic03.jpg"
      url = "blogs/blog7"

    [[params.tiles.showcase]]
      title = "IMDB ratings: Differences between directors"
      subtitle = "Which director has better moving ratings, Tim Burton or Steven Spielberg?"
      image = "pic04.jpg"
      url = "blogs/blog6"

#    [[params.tiles.showcase]]
#      title = "Consequat"
#      subtitle = "Ipsum Dolor Sit Amet"
#      image = "pic05.jpg"
#      url = "blogs/ipsum"

 #   [[params.tiles.showcase]]
#      title = "Etiam"
 #     subtitle = "Feugiat Amet Tempus"
 #     image = "pic06.jpg"
 #     url = "blogs/ipsum"
    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "About me"
    subtitle = """I'm Ruchen and currently reading for Master of Analytics and Management in London Business School.  
    I have working experiences as data analyst and marketing interns, 
    helping retailers and online travel agencies to monitor sales performance, 
    increase customer engagement, and identify potential marketing opportunities.
     """
    buttonText = "Get Started"
    url = "blogs"


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    # formEmail = "example@domain.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "rshangguan.mam2021@london.edu"

    [[params.contact.phone]]
    title = "Phone"
    phone = "(+86) 139-181-53000"

    [[params.contact.address]]
    title = "Address"
    street = "London Business School"
    city = "Regent's Park "
    country = "London NW1 4SA"

  # Footer section
  [params.footer]
    enable = true
    copyright = "London Business School"

    # Uses font awesome icons
    #[[params.footer.social]]
     # icon = "fa-twitter"
     # url= "https://www.twitter.com"
     # label = "Twitter"

    #[[params.footer.social]]
     # icon = "fa-facebook"
     # url= "https://www.facebook.com"
      #label = "Facebook"

   # [[params.footer.social]]
     # icon = "fa-instagram"
     # url= "https://www.instagram.com"
     # label = "Instagram"
    
    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com/in/ruchensg"
      label = "LinkedIn"
      
    [[params.footer.social]]
      icon = "fa-github"
      url= "https://github.com/Ruchensg/my_website"
      label = "GitHub"


    [[params.footer.quicklinks]]
      text = "Design: "
      url= "https://www.html5up.net"
      alt = "HTML5 UP"
